<a href="https://colab.research.google.com/github/darkeyr0728/etl-data-pipeline1714662012/blob/main/notebooks/Bodegas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://raw.githubusercontent.com/darkeyr0728/etl-data-pipeline1714662012/refs/heads/main/data/raw/E_bodegas.csv

In [1]:
import pandas as pd

In [2]:
url = "https://raw.githubusercontent.com/darkeyr0728/etl-data-pipeline1714662012/refs/heads/main/data/raw/E_bodegas.csv"

df = pd.read_csv(url)

df.head()

  id_bodega       bodega   ubicacion capacidad_m2
0    BOD100   Central 0     Usulután      1292 m2
1    BOD101        Sur 1  San Miguel         2047
2    BOD102    Central 2   Sonsonate       651 m2
3    BOD103  Occidente 3  San Miguel         2250
4    BOD104        Sur 4   Santa Ana          239

In [3]:
#Exploración de Datos

df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_bodega     18 non-null     object
 1   bodega        20 non-null     object
 2   ubicacion     20 non-null     object
 3   capacidad_m2  20 non-null     object
dtypes: object(4)
memory usage: 772.0+ bytes

id_bodega       2
bodega          0
ubicacion       0
capacidad_m2    0
dtype: int64

In [12]:
#Limpieza de datos

bodegas = df.copy()

bodegas.columns = bodegas.columns.str.strip().str.lower()

for col in bodegas.select_dtypes(include='object').columns:
    bodegas[col] = bodegas[col].astype(str).str.strip()

bodegas = bodegas.replace(r'^\s*$', pd.NA, regex=True)

df['id_bodega'] = df['id_bodega'].str.strip()

bodegas = bodegas.drop_duplicates()

In [13]:
#Separar datos validos
validos = bodegas[
    bodegas['id_bodega'].notna() &
    bodegas['capacidad_m2'].notna()
].copy()

rechazados = bodegas[
    bodegas['id_bodega'].isna() &
    bodegas['capacidad_m2'].notna()
].copy()

In [17]:
#Motivo de Rechazo
def motivo(row):

    motivos = []

    if pd.isna(row['id_bodega']):
        motivos.append("bodega_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

In [18]:
#Exportar Archivos
validos.to_csv("bodegas_curated.csv", index=False)

rechazados.to_csv("bodegas_rejects.csv", index=False)

In [19]:
#Conectar con Postgress
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_seguros_d64b_user:p6QnZIQqgOGUKctlfJR0R166FJ7kgt51@dpg-d6qu9dfgi27c73aabfog-a.oregon-postgres.render.com/etl_seguros_d64b"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 60.2 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

In [20]:
#Cargar Datos Postgress

validos.to_sql(
    'bodegas_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'bodegas_rejects',
    engine,
    if_exists='append',
    index=False
)

0

In [23]:
#Validar la carga
pd.read_sql(
"SELECT * FROM bodegas_curated LIMIT 10",
engine
)

  id_bodega       bodega    ubicacion capacidad_m2
0    BOD100    Central 0     Usulután      1292 m2
1    BOD101        Sur 1   San Miguel         2047
2    BOD102    Central 2    Sonsonate       651 m2
3    BOD103  Occidente 3   San Miguel         2250
4    BOD104        Sur 4    Santa Ana          239
5    BOD105    Central 5  La Libertad         1546
6    BOD106    Central 6   San Miguel         1783
7    BOD107  Occidente 7  La Libertad         2181
8    BOD108    Oriente 8    Santa Ana         1359
9    BOD109    Oriente 9    Santa Ana         2097